### ISSUE TITLE
Crash when failing to get credentials

### ISSUE THREAD

**Issue by Raffo** [hjacobs/kube-aws-autoscaler#16]
I'm not sure this is a relevant issue and it looks like it recovered after, but maybe the output is interesting. Please feel free to close otherwise. 

```
ERROR:autoscaler:Failed to autoscale
Traceback (most recent call last):
  File "/kube_aws_autoscaler/main.py", line 365, in main
    autoscale(buffer_percentage, buffer_fixed, dry_run=args.dry_run)
  File "/kube_aws_autoscaler/main.py", line 324, in autoscale
    nodes_by_asg_zone = get_nodes_by_asg_zone(autoscaling, all_nodes)
  File "/kube_aws_autoscaler/main.py", line 113, in get_nodes_by_asg_zone
    response = autoscaling.describe_auto_scaling_instances(InstanceIds=list(instances.keys()))
  File "/usr/lib/python3.5/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3.5/site-packages/botocore/client.py", line 530, in _make_api_call
    operation_model, request_dict)
  File "/usr/lib/python3.5/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/lib/python3.5/site-packages/botocore/endpoint.py", line 166, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/lib/python3.5/site-packages/botocore/endpoint.py", line 150, in create_request
    operation_name=operation_model.name)
  File "/usr/lib/python3.5/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/lib/python3.5/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/lib/python3.5/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/lib/python3.5/site-packages/botocore/signers.py", line 147, in sign
    auth.add_auth(request)
  File "/usr/lib/python3.5/site-packages/botocore/auth.py", line 316, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

**Comment by hjacobs** [comment]
I guess the behavior is "OK" as it looks like the known issue with `kube2iam`. The container will be restarted and it should recover automatically. Error handling and message *could* be nicer, but don't like a major issue to me right now.

**Comment by hjacobs** [comment]
Closing as this is a problem with `kube2iam` (or IAM instance profile).
