### ISSUE TITLE
Chunk DescribeInstances (50 instances at a time)

### ISSUE THREAD

**Issue by hjacobs** [hjacobs/kube-aws-autoscaler#25]
It appears that AWS/boto can describe only 50 instances at the time (hard limit). For large clusters, we ran into the issue since we can easily exceed 50 node cluster.

Proposed solution: split instances into 50 items batches for processing.

See #24

**Comment by hjacobs** [comment]
I just tried it out and the error looks like:

```python
>>> len(instance_ids)
76
>>> a = boto3.client('autoscaling')
>>> a.describe_auto_scaling_instances(InstanceIds=instance_ids)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/botocore/client.py", line 557, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the DescribeAutoScalingInstances operation: The number of instance ids that may be passed in is limited to 50

**Comment by hjacobs** [comment]
Fixed in https://github.com/hjacobs/kube-aws-autoscaler/releases/tag/0.8
