### ISSUE TITLE
KeyError: 'asg_name'

### ISSUE THREAD

**Issue by hjacobs** [hjacobs/kube-aws-autoscaler#3]
```python
ERROR:autoscaler:Failed to autoscale
Traceback (most recent call last):
  File "/kube_aws_autoscaler/main.py", line 299, in main
    autoscale(buffer_percentage, buffer_fixed, dry_run=args.dry_run)
  File "/kube_aws_autoscaler/main.py", line 265, in autoscale
    usage_by_asg_zone = calculate_usage_by_asg_zone(pods, nodes)
  File "/kube_aws_autoscaler/main.py", line 117, in calculate_usage_by_asg_zone
    asg_name = node['asg_name']
KeyError: 'asg_name'
```

**Comment by hjacobs** [comment]
This can apparently happen when the API server still returns the node but the node's EC2 instance is actually not running anymore (i.e. we can't find it in any ASG).
